webtalk_init -webtalk_dir C:/Users/Lenovo/Documents/GitHub/project_DT2_adder_4bit/project_DT2_adder_4bit.sim/sim_1/behav/xsim/xsim.dir/adder_4bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 26 09:08:43 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e77ee73a-fdc3-49a3-9fd9-bac64c7dfd90" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d1d9555edf0d4b7381a5008a6d5ef332" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5604_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2997598837 -regid "" -xml C:/Users/Lenovo/Documents/GitHub/project_DT2_adder_4bit/project_DT2_adder_4bit.sim/sim_1/behav/xsim/xsim.dir/adder_4bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Lenovo/Documents/GitHub/project_DT2_adder_4bit/project_DT2_adder_4bit.sim/sim_1/behav/xsim/xsim.dir/adder_4bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Lenovo/Documents/GitHub/project_DT2_adder_4bit/project_DT2_adder_4bit.sim/sim_1/behav/xsim/xsim.dir/adder_4bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
